# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Auto-tagging

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Auto tag
        # You may pin to the exact commit or the version.
        # uses: Klemensas/action-autotag@380682c329fccb8b270e70e59d40d0e918dc5a0f
        uses: Klemensas/action-autotag@1.2.3
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          tag_prefix: 'releases/'
